<?php

declare(strict_types=1);

namespace Sisly\DTOs;

use Sisly\Enums\ContentType;

/**
 * Data representing a media content prescription generated by a coach.
 */
final class Prescription
{
    public function __construct(
        public readonly ContentType $contentType,
        public readonly string $reason,
    ) {}

    /**
     * Create instance from array.
     *
     * @param array{content_type: string, reason: string} $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            contentType: ContentType::from($data['content_type']),
            reason: $data['reason'],
        );
    }

    /**
     * Convert to array for serialization.
     *
     * @return array{content_type: string, reason: string}
     */
    public function toArray(): array
    {
        return [
            'content_type' => $this->contentType->value,
            'reason' => $this->reason,
        ];
    }
}
